"""Public API for the investment monitoring foundation."""

from .application import (
    ConfiguredCollectionResult,
    WorkflowResult,
    run_configured_collection,
    run_ticker_collection,
    run_workflow,
)
from .config import (
    ALLOWED_LIST_TYPES,
    CollectionSettings,
    ConfigurationError,
    SourceConfig,
    UniverseEntry,
    load_environment_file,
    load_settings,
    load_universe,
)
from .connectors.base import ConnectorUnavailableError, SourceConnector
from .connectors.mock import MockConnector
from .connectors.mock_community import MockCommunityConnector
from .kr_universe import (
    KrUniverseError,
    kr_universe_name_map,
    load_kr_universe,
    refresh_kr_universe,
)
from .sources.companies_house import (
    CompaniesHouseClient,
    CompaniesHouseCompanyResolver,
    CompaniesHouseConnector,
    CompaniesHouseDataError,
    CompaniesHouseError,
    CompaniesHouseRequestError,
    CompanyNumberCache,
)
from .sources.dart import (
    CorpCodeCache,
    DARTCompanyResolver,
    DARTConnector,
    DartClient,
    DartDataError,
    DartError,
    DartRequestError,
)
from .sources.investegate import (
    InvestegateClient,
    InvestegateConnector,
    InvestegateDataError,
    InvestegateError,
    InvestegateRequestError,
)
from .sources.kind import (
    KindClient,
    KindConnector,
    KindDataError,
    KindError,
    KindRequestError,
)
from .sources.kr_news import (
    HankyungClient,
    HankyungConnector,
    HankyungDataError,
    HankyungError,
    HankyungRequestError,
    NaverNewsClient,
    NaverNewsConnector,
    NaverNewsDataError,
    NaverNewsError,
    NaverNewsRequestError,
    TheBellClient,
    TheBellConnector,
    TheBellDataError,
    TheBellError,
    TheBellRequestError,
)
from .sources.news import (
    FinnhubClient,
    FinnhubNewsConnector,
    FinnhubNewsDataError,
    FinnhubNewsError,
    FinnhubNewsRequestError,
)
from .sources.sec import (
    SECClient,
    SECConfigurationError,
    SECConnector,
    SECDataError,
    SECError,
    SECRequestError,
    TickerCollectionFailure,
)
from .models import (
    ALLOWED_MARKETS,
    CollectionRequest,
    InformationItem,
    MARKET_CN,
    MARKET_HK,
    MARKET_KR,
    MARKET_UK,
    MARKET_UNKNOWN,
    MARKET_US,
)
from .pipeline import CollectionFailure, CollectionPipeline
from .registry import SourceRegistry, create_default_registry
from .repository import InformationRepository, SaveResult
from .report import ReportResult, generate_html_report
from .sqlite_repository import SQLiteInformationRepository
from .web_repository import WebRepository

__all__ = [
    "ALLOWED_LIST_TYPES",
    "ALLOWED_MARKETS",
    "CollectionFailure",
    "CollectionPipeline",
    "CollectionRequest",
    "CollectionSettings",
    "ConfigurationError",
    "ConfiguredCollectionResult",
    "ConnectorUnavailableError",
    "CompaniesHouseClient",
    "CompaniesHouseCompanyResolver",
    "CompaniesHouseConnector",
    "CompaniesHouseDataError",
    "CompaniesHouseError",
    "CompaniesHouseRequestError",
    "CompanyNumberCache",
    "CorpCodeCache",
    "DARTCompanyResolver",
    "DARTConnector",
    "DartClient",
    "DartDataError",
    "DartError",
    "DartRequestError",
    "InvestegateClient",
    "InvestegateConnector",
    "InvestegateDataError",
    "InvestegateError",
    "InvestegateRequestError",
    "FinnhubClient",
    "FinnhubNewsConnector",
    "FinnhubNewsDataError",
    "FinnhubNewsError",
    "FinnhubNewsRequestError",
    "HankyungConnector",
    "InformationRepository",
    "InformationItem",
    "KindClient",
    "KindConnector",
    "KindDataError",
    "KindError",
    "KindRequestError",
    "KrUniverseError",
    "MARKET_CN",
    "MARKET_HK",
    "MARKET_KR",
    "MARKET_UK",
    "MARKET_UNKNOWN",
    "MARKET_US",
    "MockConnector",
    "MockCommunityConnector",
    "NaverNewsConnector",
    "SECClient",
    "SECConfigurationError",
    "SECConnector",
    "SECDataError",
    "SECError",
    "SECRequestError",
    "SourceConfig",
    "SourceConnector",
    "SourceRegistry",
    "SQLiteInformationRepository",
    "SaveResult",
    "TickerCollectionFailure",
    "TheBellConnector",
    "UniverseEntry",
    "WorkflowResult",
    "WebRepository",
    "create_default_registry",
    "kr_universe_name_map",
    "load_kr_universe",
    "load_settings",
    "load_environment_file",
    "load_universe",
    "refresh_kr_universe",
    "generate_html_report",
    "run_configured_collection",
    "run_ticker_collection",
    "run_workflow",
    "ReportResult",
]
